default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: mysql2
  encoding: utf8
  database: chat_app_1_development
  username: root
  password: 123456
  port: 3306
  host: db

development:
  <<: *default

test:
  <<: *default
  database: chat_app_1_test

production:
  <<: *default

